### ISSUE TITLE
No permissions to write 

### ISSUE THREAD

**Issue by aadityasaraiya** [ros-industrial/workcell_explorer#4]
Hi,

So I was just trying to push some updates to the repository and I encountered the following error. 

~~~
remote: Permission to ros-industrial/workcell_explorer.git denied to aadityasaraiya.
fatal: unable to access 'https://github.com/ros-industrial/workcell_explorer.git/': The requested URL returned error: 403
~~~

@gavanderhoorn Just wanted to check with you once if the permissions had changed somehow. 

Thanks and regards,
Aaditya Saraiya

**Comment by gavanderhoorn** [comment]
Did you participate in World ROS-Industrial Day 2018? Perhaps permissions changed because of that.

You only had `read` permission on this repository, I've just changed it back to `write`.

> I was just trying to push some updates to the repository

just an observation and suggestion: I don't want to contradict what any of your GSoC mentors might have told you, but perhaps consider using Pull Requests to submit updates. If a review is ever needed, that is much easier with PRs, and even if there is no review needed, discussing your updates is also facilitated greatly by using them.

Even if you're the only developer working on this repository using PRs as part of your workflow is a good habit to develop.

**Comment by aadityasaraiya** [comment]
Thanks a lot for the same @gavanderhoorn. No, actually I didn't participate in the World ROS-Industrial Day 2018. 

I agree with you regarding the fact that it's better to submit a PR. I will try to follow the same. Thanks for the suggestion.
